### ISSUE TITLE
using more abstractions

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/FaceDetect#12]
I really like your JS code, you have comments in the file to help understand what it's doing, you have meaningful variable names and you split it up pretty nicely.

but there is a lot of code that is being repeated for example

```js
(Math.round(weatherObj.main.temp_max * (9/5) - 459.67)).toString() + " F (" + Math.round((weatherObj.main.temp_max - 273.1)) + " C)

```

and you also have written 5 fetch requests, while instead you can write 1 by using callbacks

```js
// can be named whatever
function request(url, callback) {

fetch(url)
  .then(function (response) {
    return response.json()
  })
  .then(function(data) {
    callback(null, data)
  })
  .catch(function(error) {
    callback(error)
  })

}

```

this way makes it so we have to write the fetch request only 1 time. give the url to fetch and function to run when the request is done/fulfilled or rejected.

**Comment by JakePowis** [comment]
Thanks Celsius and Fahrenheit calculation functions added:

https://github.com/WebAhead5/LocationInfo/blob/master/src/js/detectFaces.js#L42-L44

https://github.com/WebAhead5/LocationInfo/blob/master/src/js/detectFaces.js#L188-L198


Will now look at abstraction of the fetch function

**Comment by JakePowis** [comment]
Code now refactored using callbacks - thanks!
