### ISSUE TITLE
do we need locationpic.js?

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/FaceDetect#13]
seems like you don't use [this file](https://github.com/WebAhead5/LocationInfo/blob/master/src/js/locationpic.js#L2), and the functionality of that file exists in detectFaces.js

**Comment by JungleSoftTech** [comment]
it was for trail
obviously we forgot to remove it

**Comment by MoradAbed** [comment]
Deleted all the unnecessary files. 
Thanks.
