### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/FaceDetect#15]
[this is a really good start for error handling](https://github.com/WebAhead5/LocationInfo/blob/master/src/js/detectFaces.js#L59-L65), but if any of the other fetch requests give out an error then we have no way of handling that.

maybe make a function that creates a error message onto the page custom for every different fetch request ? (i mean 1 error handling function that takes an errorMessage as an argument)

**Comment by JungleSoftTech** [comment]
that is correct 
i actually paid attention to that
if you pay close attention to the weather api it handles the error by clearing out previous results and displaying a msg
we should have done the same to the other apis used

**Comment by Karyum** [comment]
@VoJunSoft closing an issue means the discussion is done and not change will be made in this specific case :sweat_smile: are you sure you want to close this ?

**Comment by JungleSoftTech** [comment]
loool sorry

**Comment by JakePowis** [comment]
Dear @Karyum - the team at LocationInfo has now taken your valued feedback into account and has lovingly implemented an Error Handling function for you and all your friends to enjoy! 

https://github.com/WebAhead5/LocationInfo/blob/master/src/js/detectFaces.js#L168-L190

I will now close this issue <3
